name: GitHub-Page

# Controls when the workflow will run
on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    
    env:
      webRenderer: auto
      workingDir: .
      targetBranch: gh-pages
      baseHref: /bitecope-clone/

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.3'
          channel: 'beta'

      - run: flutter config --enable-web
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: flutter pub get
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: flutter build web --release --web-renderer=${{env.webRenderer}} --base-href=${{env.baseHref}}
        shell: bash
        working-directory: ${{env.workingDir}}

      - run: cp -r assets/* build/web/assets/
        shell: bash
        working-directory: ${{env.workingDir}}

      - run: git config user.name github-actions
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: git config user.email github-actions@github.com
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: git --work-tree build/web add --all
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: git commit -m "Automatic deployment by github-actions"
        shell: bash
        working-directory: ${{env.workingDir}}
      - run: git push origin HEAD:${{env.targetBranch}} --force
        shell: bash
        working-directory: ${{env.workingDir}}
